---
title: "project"
author: "Маслова И"
date: "2022-11-22"
output: word_document
---

# Подключаем библиотеки, читаем данные

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Hmisc)
library(dplyr)
library(tidyr)
library(tibble)
library(readr)
library(tidyverse)
library(xlsx)
```



# Загрузка данных с рекодировкой

```{r}
data <-  read.csv('CharityHospital_DATA_2022-11-02_1448_приложение к R.csv', fileEncoding= "utf-8")
```

# Подсчитываем возраст

```{r}
data$date_bd <- ifelse(data$date_bd == '', NA, data$date_bd) # замена пустый ячеек на NA

for (i in 1:length(data$date_bd)) {
  if (is.na(data$date_bd[i]) == FALSE) {
    date_1 <- as.Date(data$date_bd[i])
    date_2 <- Sys.Date()
    a = seq(from = date_1, to = date_2, by = 'year')
    data$age_calc[i] <- length(a)-1
  }
}

```


# Назовем пропуски характеристиками

```{r}

data$redcap_repeat_instrument <-  ifelse(data$redcap_repeat_instrument == '', 'Характеристики', data$redcap_repeat_instrument)


```



# Переименуем столбцы, загрузим новый датасет
 
```{r}

data2 <- read.csv("CharityHospital_DATA_LABELS_2022-11-02_1446_labels.csv", encoding = "UTF-8", check.names=FALSE)
colnams <- colnames(data2)
colnames(data) <- colnams

data %>% write.csv('new_data.csv', fileEncoding= "CP1251")

```

# Без пропусков?

```{r}
df <- data[, !sapply(data, function(x)all(is.na(x))), drop=F]
```


# Категориальные в факторы

Часть 1
```{r}
df <- df %>% mutate( across(c(`Пол`, `Гражданство`, `Паспорт (любой)`, `Полис ОМС`, `СНИЛС`, `Восстановление документов через Кинонию (choice=отправили в паспортный стол)`, `Восстановление документов через Кинонию (choice=вернулся с информацией из паспортного стола)`, `Восстановление документов через Кинонию (choice=выдана госпошлина)`, `Регистрация`, `Согласие на обработку персональных данных заполнено?`, `Complete?`,  `Анамнез со слов по ТБ`, `ВИЧ-инфекция`, `Гепатит С`, `Сифилис`,`Прием АРВТ`, `никотиновая зависимость`, `алкогольная зависимость`, `ПАВ инъекционно (вв,вм героин, метадон, соли и пр.)`, `ПАВ НЕинъекционно (курение, per os)`, `Complete?.1`, `Complete?.2`), function(x) as.factor(x)))
```

Часть 2
```{r}
df <- df %>% mutate( across(c( `Место приема`, `Где ночует пациент сегодня? (или где ночевал вчера?)`, `Вы ассистент? (то есть не врач; человек, не имеющий возможности в силу своей квалификации принимать медицинские решения о здоровье пациента и нести за них ответственность)?`, `Опьянение (алкогольное, наркотическое)`, `Жалобы &nbsp; (choice=дыхательная система)`, `Жалобы &nbsp; (choice=желудочно-кишечный тракт (ЖКТ))`, `Жалобы &nbsp; (choice=сердечно-сосудистая система (ССС))`, `Жалобы &nbsp; (choice=мочеполовая система)`, `Жалобы &nbsp; (choice=опорно-двигательная система)`, `Жалобы &nbsp; (choice=ЦНС=психиатрия=ментальные нарушения)`, `Жалобы &nbsp; (choice=зрение)`, `Жалобы &nbsp; (choice=эндокринная система)`, `Жалобы &nbsp; (choice=болевой синдром)`, `Жалобы &nbsp; (choice=острая травма)`, `Жалобы &nbsp; (choice=сыпь)`, `Жалобы &nbsp; (choice=рана)`, `Жалобы &nbsp; (choice=жалоб не предъявляет\\иные жалобы)`), function(x) as.factor(x)))
```
Часть 3

```{r}
df <- df %>% mutate( across(c( `Слизистая ротоглотки`, `Налеты на миндалинах`, `Дыхание через нос`, `Грудная клетка`, `Кашель (choice=сухой, малопродуктивный)`, `Кашель (choice=влажный, продуктивный)`, `Кашель (choice=приступообразный)`, `Кашель (choice=преимущественно утром)`, `Кашель (choice=постоянно в течение дня)`, `Кашель (choice=мучительный, нарушает сон)`, `Мокрота (choice=слизистая)`, `Мокрота (choice=гнойная)`, `Мокрота (choice=слизисто-гнойная)`, `Мокрота (choice=скудное количество)`, `Мокрота (choice=умеренное количество)`, `Мокрота (choice=обильное количество)`, `Аускультативно дыхание`, `Хрипы`, `Живот`, `Рвота (choice=неукротимая)`, `Рвота (choice=однократно)`, `Рвота (choice=съеденной пищей без пат. примесей)`, `Рвота (choice=с алой кровью)`, `Рвота (choice=с измененной кровью)`,`Физиологические отправления (choice=мочеиспускание не нарушено, стул оформленный)`, `Физиологические отправления (choice=признаки дизурии)`, `Физиологические отправления (choice=диарея)`, `Физиологические отправления (choice=мелена)`, `Отеки (choice=пастозность голеней)`, `Отеки (choice=отеки ног до паха)`, `Отеки (choice=отечность выше паха)`, `Отеки (choice=анасарка)`, `Отеки (choice=асцит)`, `Диагноз по МКБ-10 #1`, `Диагноз по МКБ-10 #2`, `Наши действия (choice=ведем амбулаторно)`, `Наши действия (choice=тестируем на инфекции)`, `Наши действия (choice=вакцинируем)`, `Наши действия (choice=проводим перевязку)`, `Наши действия (choice=оцениваем остроту зрения\\выдаем очки)`, `Наши действия (choice=выдаем медикаменты)`, `Наши действия (choice=вызываем СМП)`, `Наши действия (choice=пациент отказался от госпитализации)`), function(x) as.factor(x)))
```
 Часть 4
```{r}
df <- df %>% mutate( across(c( `Диагноз по МКБ-10 #3`, `Пациенту выдано: (choice=согласие на медицинскую тайну)`, `Пациенту выдано: (choice=направление ф.057/у)`, `Пациенту выдано: (choice=справка ББ с фото)`, `Пациенту выдано: (choice=консультативное заключение)`, `Пациенту выдано: (choice=жетон на метро)`, `Пациенту выдано: (choice=БСК на метро)`, `Пациенту выдано: (choice=лайфпак М\\Ж)`, `Пациенту выдано: (choice=спальник)`, `Пациенту выдано: (choice=мобильный телефон)`, `Пациенту выдано: (choice=SIM-карта к телефону)`, `Пациенту выдано: (choice=трость\\костыль)`, `Пациенту выдано: (choice=тест на беременность)`, `Пациенту выдано: (choice=средства интимной гигиены (прокладки, тампоны) комплект)`, `Complete?.3`, `Характеристики необходимых очков`, `OD`, `Прибор для измерения ВГД`, `OS`, `Мидриаз`, `Куда направили? &nbsp;`, `Откуда выдаем очки?`, `Футляр`, `Статус заказа по очкам (отмечают координаторы по очкам ББ`, `Complete?.4`, `На что тестируем? (choice=ВИЧ-инфекция)`, `На что тестируем? (choice=Вирусный гепатит С)`, `На что тестируем? (choice=Вирусный гепатит В)`, `На что тестируем? (choice=Сифилис)`, `На что тестируем? (choice=COVID-19)`, `Результат экспресс-теста на ВИЧ-инфекцию`, `Результат экспресс-теста на вирусный гепатит В`, `Результат экспресс-теста на вирусный гепатит С`, `Результат экспресс-теста на сифилис`, `Результат экспресс-теста на антигены COVID-19 (номер на бланке&nbsp; - ID пациента + дата, например '876 от 26.07.2022')`, `Взят расширенный серологический анализ на сифилис (две пробирки венозной крови+направление)`, `Complete?.5`, `Вакцинация против (choice=сезонного гриппа)`, `Вакцинация против (choice=COVID-19)`, `Вакцинация против (choice=пневмококковой инфекции (Превенар 13))`, `Вакцинация против (choice=менингококковой инфекции (Менактра))`, `Вакцинация против (choice=дифтерии, столбняка (АДС-М))`, `Вакцинация против (choice=ничего из перечисленного/отказ)`, `COVID-19: Вакцина`, `COVID-19: Кратность введения`, `Грипп: Вакцина`, `Complete?.6`, `Complete?.7`, `Выпускник детского дома`, `Образование`, `Семейное положение`, `Был(а) в МЛС`), function(x) as.factor(x)))
```
 Часть 5
 
```{r}
df <- df %>% mutate( across(c( `Причины бездомности (choice=Мошенничество/вымогательство (с жильем))`, `Причины бездомности (choice=Осуждение к лишению свободы)`, `Причины бездомности (choice=Семейные проблемы)`, `Причины бездомности (choice=Вынужденный переселенец)`, `Причины бездомности (choice=Выселение из служебного жилья)`, `Причины бездомности (choice=Переезд в поисках работы)`, `Причины бездомности (choice=Желание путешествовать\\переезд в другой город)`, `Причины бездомности (choice=Сгорело\\пришло в негодность жилье)`, `Причины бездомности (choice=Выпускник интерната)`, `Причины бездомности (choice=Взыскание жилья за долги)`, `Причины бездомности (choice=Конфликт с соседями)`, `Причины бездомности (choice=Хим.зависимость)`, `Причины бездомности (choice=Заболевания\\травмы)`, `Причины бездомности (choice=Потеря работы)`, `Причины бездомности (choice=Потеря возможности снимать жилье)`, `Причины бездомности (choice=Продажа жилья)`, `Причины бездомности (choice=Украли крупную сумму денег)`, `Причины бездомности (choice=Утрата документов)`, `Причины бездомности (choice=Обманул работодатель)`, `Причины бездомности (choice=Отказ от ответа)`, `Источники существования (choice=Постоянная работа)`, `Источники существования (choice=Временная работа)`, `Источники существования (choice=Пенсия, пособие)`, `Источники существования (choice=Подаяние)`, `Источники существования (choice=Помощь близких и друзей)`, `Источники существования (choice=Собирательство)`, `Источники существования (choice=Благотворительность (в т.ч. церковная))`, `Источники существования (choice=Рабочие дома)`, `Источники существования (choice=Отказ от ответа)`, `Complete?.8`, `Беременность`, `Complete?.9`, `Complete?.10`, `Check if this person identifies as a different gender. (choice=)`, `Communicable Languages (choice=English)`, `Communicable Languages (choice=Spanish)`, `Communicable Languages (choice=Creole)`, `Communicable Languages (choice=Portuguese)`, `Communicable Languages (choice=Other)`, `Complete?.11`, `Where are you currently staying the night? (choice=Shelter)`, `Where are you currently staying the night? (choice=Outside)`, `Where are you currently staying the night? (choice=Car)`), function(x) as.factor(x)))
```
 
Часть 6
```{r}
df <- df %>% mutate( across(c( `Where are you currently staying the night? (choice=Building)`, `Where are you currently staying the night? (choice=Other)`, `Services that come to you outside (select all that apply) (choice=Showers)`, `Services that come to you outside (select all that apply) (choice=Food)`, `Services that come to you outside (select all that apply) (choice=Laundry)`, `Services that come to you outside (select all that apply) (choice=Hygiene)`, `Services that come to you outside (select all that apply) (choice=Legal help)`, `Services that come to you outside (select all that apply) (choice=Needle Exchange)`, `Services that come to you outside (select all that apply) (choice=Medical)`, `In the past year, have you visited the ER for any of the following reasons: (choice=Wound Care)`, `In the past year, have you visited the ER for any of the following reasons: (choice=Medications)`, `In the past year, have you visited the ER for any of the following reasons: (choice=Other)`, `What social services do you use? (select all that apply) (choice=Soup Kitchens)`, `What social services do you use? (select all that apply) (choice=Food bank)`, `What social services do you use? (select all that apply) (choice=Day Shelter)`, `What social services do you use? (select all that apply) (choice=Clothing Closet)`, `What social services do you use? (select all that apply) (choice=Job assistance)`, `What social services do you use? (select all that apply) (choice=Legal assistance)`, `Have you had any involvement with the judicial system? (select all that apply) (choice=Tickets)`, `Have you had any involvement with the judicial system? (select all that apply) (choice=Imprisonment)`, `Have you had any involvement with the judicial system? (select all that apply) (choice=No involvement)`, `Do you have any of the following forms of income? (select all that apply) (choice=Welfare/state support)`, `Do you have any of the following forms of income? (select all that apply) (choice=SNAP Food Benefits (Food Stamps))`, `Do you have any of the following forms of income? (select all that apply) (choice=Odd Jobs)`, `Do you have any of the following forms of income? (select all that apply) (choice=Asking for money on the street (Panhandling))`, `Do you have any of the following forms of income? (select all that apply) (choice=Selling drugs)`, `Do you have any of the following forms of income? (select all that apply) (choice=Sex Work)`, `Do you have any of the following forms of income? (select all that apply) (choice=Other)`), function(x) as.factor(x)))
```
Часть 7

```{r}
df <- df %>% mutate( across(c( `How do you store your money? (please select all that apply) (choice=Cash - on person)`, `How do you store your money? (please select all that apply) (choice=Cash - hidden or with family/friend)`, `How do you store your money? (please select all that apply) (choice=Bank Account - Debit Card)`, `What forms of identification do you possess? (choice=Drivers License)`, `What forms of identification do you possess? (choice=State Identification Card)`, `What forms of identification do you possess? (choice=Social Security Card)`, `What forms of identification do you possess? (choice=Birth Certificate)`, `Where do you usually get food? (choice=Soup Kitchen)`, `Where do you usually get food? (choice=Outreach Group)`, `Where do you usually get food? (choice=Shelter)`, `Where do you usually get food? (choice=Day Center)`, `Where do you usually get food? (choice=Church)`, `Where do you usually get food? (choice=Convenience Store)`, `Do you eat any of the following foods? (choice=Carbohydrates (Bread, Rice, Pasta))`, `Do you eat any of the following foods? (choice=Meat)`, `Do you eat any of the following foods? (choice=Vegetables)`, `Do you eat any of the following foods? (choice=Fruit)`, `Do you eat any of the following foods? (choice=Sweets)`, `Do you eat any of the following foods? (choice=Chips/Packaged Snacks)`, `What is your normal source of water? (choice=New bottles of water)`, `What is your normal source of water? (choice=Water fountain)`, `What is your normal source of water? (choice=Bathroom sink)`, `What is your normal source of water? (choice=Hose)`, `What is your normal source of water? (choice=Other)`, `Where do you shower/bathe? (choice=Day shelter)`, `Where do you shower/bathe? (choice=Overnight shelter)`, `Where do you shower/bathe? (choice=Beach bathroom/shower)`, `Where do you shower/bathe? (choice=Other public bathroom)`, `Where do you shower/bathe? (choice=Other private (business) bathroom)`, `What type of shelter is used? (choice=Inside a building)`, `What type of shelter is used? (choice=Next to/beside a building with overhang protection)`, `What type of shelter is used? (choice=Overpass)`, `What type of shelter is used? (choice=Tent)`, `What type of shelter is used? (choice=Blanket Fort)`, `What type of shelter is used? (choice=Blanket)`, `What type of shelter is used? (choice=Umbrella)`, `What position are you in while sleeping? (choice=Lying down on bench)`, `What position are you in while sleeping? (choice=Lying down on ground)`, `What position are you in while sleeping? (choice=Sitting up on bench)`, `What position are you in while sleeping? (choice=Sitting up on ground)`, `What time of day do you sleep? (choice=Night (8pm-5am))`, `What time of day do you sleep? (choice=Morning (5am-10am))`, `What time of day do you sleep? (choice=During Afternoon (10am-5pm))`, `What time of day do you sleep? (choice=During Evening (5pm-8pm))`, `What time of day do you sleep? (choice=No pattern - always changes)`, `What fears do you have? (choice=Being robbed)`, `What fears do you have? (choice=Being attacked)`, `What fears do you have? (choice=Being sexually assaulted)`, `What fears do you have? (choice=Police, law enforcement harassment, fines, arrest)`, `What fears do you have? (choice=Other)`, `Complete?.12`, `Визуально-аналоговая шкала боли`, `Состояние`, `Сознание`, `Complete?.13`), function(x) as.factor(x)))
```


```{r}
df %>% write.csv('new_df2.csv', fileEncoding= "CP1251")
```









